### ISSUE TITLE
AttributeError: module 'tensorflow_core.keras.utils' has no attribute 'register_keras_serializable'

### ISSUE THREAD

**Issue by Liaoqing-up** [mlech26l/keras-ncp#12]
i have install tensorflow2.0.0, but when i run examples, it give the mistake "AttributeError: module 'tensorflow_core.keras.utils' has no attribute 'register_keras_serializable'", how can i fix it ?

**Comment by mlech26l** [comment]
Please upgrade to the latest TensorFlow version
