### ISSUE TITLE
  Is the implementation of Eq. 3 inconsistent with the paper?

### ISSUE THREAD

**Issue by lucifer2859** [mlech26l/keras-ncp#17]
numerator = (
                cm_t * v_pre
                + self._params["gleak"] * self._params["vleak"]
                + w_numerator ### Why do you use addition instead of multiplication here？
            )
            denominator = cm_t + self._params["gleak"] + w_denominator

            # Avoid dividing by 0 
            v_pre = numerator / (denominator + self._epsilon)

**Comment by mlech26l** [comment]
Hi @lucifer2859,

yes, there is a typo in the paper (+ missing). 
Thanks for noticing.
