### ISSUE TITLE
Questions about ltc_cell.py

### ISSUE THREAD

**Issue by lucifer2859** [mlech26l/keras-ncp#18]
def _sigmoid(self, v_pre, mu, sigma):
        v_pre = torch.unsqueeze(v_pre, -1)  # For broadcasting
        mues = v_pre - mu
        x = sigma * mues
        return torch.sigmoid(x)

Why is data multiplied by sigma rather than divided by sigma in the process of normalization?

**Comment by mlech26l** [comment]
This is not a normalization layer. Sigma here corresponds to the per-synapse parameter gamma in the paper.
