### ISSUE TITLE
AttributeError: 'FullyConnected' object has no attribute 'sensory_adjacency_matrix'

### ISSUE THREAD

**Issue by rain-in-night** [mlech26l/keras-ncp#30]
hi，ace！ I am very interested in your work and using your LTCcell to model time series. However, the following problems appear in the process of use, may I ask why? I am a beginner and I hope to get your help
Here is my code:
`

    def main(argv):
        wiring = kerasncp.wirings.FullyConnected(8, FLAGS.rnn_units)  # 16 units, 8 motor neurons
        ltc_cell = LTCCell(wiring, FLAGS.emb_dim)
    
        casflow_inputs = tf.keras.layers.Input(shape=(FLAGS.max_seq, FLAGS.emb_dim))
        bn_casflow_inputs = tf.keras.layers.BatchNormalization()(casflow_inputs)
    
        gru_2 = tf.keras.layers.Bidirectional(tf.keras.layers.RNN(ltc_cell))(bn_casflow_inputs)
    
        mlp_1 = tf.keras.layers.Dense(128, activation='relu')(gru_2)
        mlp_2 = tf.keras.layers.Dense(64, activation='relu')(mlp_1)
        outputs = tf.keras.layers.Dense(1)(mlp_2)`

There is a bug in the running：
![sa](https://user-images.githubusercontent.com/36921887/160246816-a21a0560-a4e6-48f1-b024-ae8c53780c7a.png)

`

**Comment by mlech26l** [comment]
Hi @zengxiang01 

I have pushed a potential fix (keras-ncp version 2.0.7).
Can you please update to this version and test your code?
