### ISSUE TITLE
about  WiredCfcCell and CfcCell

### ISSUE THREAD

**Issue by ZhangMengEnAPI** [mlech26l/keras-ncp#31]
Hi，I've read your recent paper-"Closed-form Continuous-time Neural Networks". It's really a excellent work about how to translate a trained LTC network into its closed-form variant and construct Cfc neural network. But I don't find open source code about WiredCfcCell and CfcCell in keras-ncp. So, is the code open? If the code is open source, Can I get a copy of the source code for academic research? 
My email is zhangmengen1024@stud.tjut.edu.cn.
Thanks again.

**Comment by mlech26l** [comment]
Hi @ZhangMengEnAPI 

Sorry, I forgot to check in these two files :laughing: I added them now.
The code for the CfC is still experimental and potentially subject to change.

If you are interested in the CfC model, please also check out the repo of my colleague: https://github.com/raminmh/CfC

**Comment by ZhangMengEnAPI** [comment]
Thank you for your reply and your excellent work @mlech26l
