### ISSUE TITLE
where is the code of Translating a trained LTC/NCP network into its closed-form variant?

### ISSUE THREAD

**Issue by ZhangMengEnAPI** [mlech26l/keras-ncp#32]
Hi @mlech26l ,
        I am reading the paper 《Closed-form Continuous-time Neural Networks》，but I don't find the code of translating a trained LTC/NCP network into its closed-form variant in keras-ncp.  Is it in keras-ncp/cfc_cell.py or isn't there corresponding code in keras-ncp? Could you please upload to github？
        Thanks in advance for helping me.

**Comment by mlech26l** [comment]
Hi @ZhangMengEnAPI 
The closed-form networks are only approximations of the LTC model and their weights are not compatible.

**Comment by raminmh** [comment]
@ZhangMengEnAPI, as @mlech26l mentioned training of closed-form networks is independent of their LTC form. 

To run the translated closed-form network for the driving example described in our "closed-form continuous-time neural networks" paper, I refer you to our CfC paper repo (https://github.com/raminmh/CfC) folder figure_1_experiments.

**Comment by ZhangMengEnAPI** [comment]
Thank you very much for your reply @mlech26l @raminmh
