### ISSUE TITLE
The numpy version

### ISSUE THREAD

**Issue by v3551G** [mlech26l/keras-ncp#4]
Hi，The numpy version？
  when, allow_pickles=True, report OSError: Failed to interpret file 'D:/Workspace/Pycharm/keras-ncp/kerasncp\\datasets\\icra2020_lidar_collision_avoidance.npz' as a pickle.
when, allow_pickles=False, report ValueError: Cannot load file containing pickled data when allow_pickle=False

**Comment by mlech26l** [comment]
Successfully tested with NumPy 1.18.1 and 1.19.2

See [examples/stacking_ncp.py](https://github.com/mlech26l/keras-ncp/blob/master/examples/stacking_ncp.py)
