### ISSUE TITLE
How to download 193GB dataset?

### ISSUE THREAD

**Issue by ScGPS** [mlech26l/keras-ncp#5]
Hi, where can I get the 193GB dataset?
![image](https://user-images.githubusercontent.com/10125111/97941781-fc5ee000-1dbe-11eb-8576-d718bcb5d1ce.png)

**Comment by mlech26l** [comment]
Send me an email

**Comment by ScGPS** [comment]
Thanks! My email: happy.every.day@126.com
I don't know why do you put the dataset on Internet? For this way, it will provide convenience to all users on the Internet.

**Comment by raminmh** [comment]
193GB is too large to be hosted on our servers. Therefore, we decided to open-source all material online and provide the data on demand to avoid traffic.
