### ISSUE TITLE
Unable to save model to file

### ISSUE THREAD

**Issue by bhorsfield** [mlech26l/keras-ncp#7]
Hi there,

I have created a simple NCP model based on the examples on your GitHub page. 
 The model trains correctly, but for some reason I am unable to save the model afterwards.

I have tried the following commands in my Python script: 

**model.save('ncp-model.h5')**  
Result:  Program terminates with the following error message:  NotImplementedError: Layer LTCCell has arguments in `__init__` and therefore must override `get_config`.

 **model.save('ncp-model')** (i.e. no h5 extension).
Result:  Program generates the following error message:  WARNING:tensorflow:From /home/anyone/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
2020-11-27 11:48:26.703819: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:tensorflow:From /home/anyone/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.

In both of the above cases, a saved model file is created on my hard drive, but TensorFlow cannot load it back in again.

Details of my setup are as follows:
* HP Omen laptop, 32 GB system memory
* NVIDIA GTX-1070 GPU, 8 GB VRAM
* Ubuntu 18.04
* TensorFlow 2.3.1
* Python 3.7 

Do you have any idea what the problem could be?  Any assistance you can provide would be greatly appreciated!

Thanks & Regards,
Brendan.

**Comment by mlech26l** [comment]
I have added a [code example](https://github.com/mlech26l/keras-ncp/blob/master/examples/save_model.py).

To use the load/save functionality you may need to update the package to the latest version:
```bash
pip3 install --upgrade keras-ncp
```

**Comment by bhorsfield** [comment]
Thanks Mathias, that worked perfectly.

Cheers,
Brendan.
